### ISSUE TITLE
Affine_theta.json no such directory

### ISSUE THREAD

**Issue by takuphilchan** [wl-zhao/DiffSwap#23]
Hello can someone please help me fix this issue 
`100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.00it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.83it/s]
image: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.10it/s]
type source img_count 1
image: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.87it/s]
type target img_count 1
Recreating aligned images...
image: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.20it/s]
type source finished, processed 1 images
image: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.21it/s]
type target finished, processed 1 images
image: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.14it/s]
type source img_count 1
image: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 32.85it/s]
type target img_count 1
running face detection
data_preprocessing/detection/run_detect_faces_portrait.sh: line 1: python: command not found
running mtcnn
sh: 1: python: not found
obtain the parameters of affine transformation
sh: 1: python: not found
len(self.src_list): 1
Traceback (most recent call last):
  File "pipeline.py", line 418, in <module>
    save_mask()
  File "pipeline.py", line 328, in save_mask
    dataset = Portrait('data/portrait')
  File "/mnt/d/DiffSwap/utils/portrait.py", line 40, in __init__
    self.affine_thetas = json.load(open(f'{root}/affine_theta.json'))
FileNotFoundError: [Errno 2] No such file or directory: 'data/portrait/affine_theta.json'`

**Comment by takuphilchan** [comment]
Fixed it it was python command issue sudo ln -s /usr/bin/python3 /usr/bin/python
